/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import sisserviciofinanciero.*;
import vistas.departametoEmpresa.frmIndexDepatamentosEmpresa;
import vistas.departametoEmpresa.frmNuevoDepartamentoEmpresa;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import vistas.cargo.frmIndexCargo;
import vistas.cargo.frmNuevoCargo;
import vistas.cliente.frmIndexCliente;
import vistas.cliente.frmNuevoCliente;
import vistas.empleado.frmIndexEmpleado;
import vistas.empleado.frmNuevoEmpleado;
import vistas.sucursal.frmIndexSucursal;
import vistas.sucursal.frmNuevoSucursal;

/**
 *
 * @author Alejandro
 */
public class frmEscritorio extends javax.swing.JFrame {

    /**
     * Creates new form frmEscritorio
     */
    public frmEscritorio() {
        initComponents();
        
        try{
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnlEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmEmpresa = new javax.swing.JMenu();
        jmiDepartamentos = new javax.swing.JMenuItem();
        jmiNuevoDepartamento = new javax.swing.JMenuItem();
        jmiCargos = new javax.swing.JMenuItem();
        jmiNuevoCargo = new javax.swing.JMenuItem();
        jmiEmpleados = new javax.swing.JMenuItem();
        jmiNuevoEmpleado = new javax.swing.JMenuItem();
        jmiUsuarios = new javax.swing.JMenuItem();
        jmiNuevoUsuario = new javax.swing.JMenuItem();
        jmiSucursal = new javax.swing.JMenuItem();
        jmiNuevaSucursal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiNuevoCliente = new javax.swing.JMenuItem();
        jmCuentas = new javax.swing.JMenu();
        jmiCuentas = new javax.swing.JMenuItem();
        jmiNuevoCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpnlEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dpnlEscritorioLayout = new javax.swing.GroupLayout(dpnlEscritorio);
        dpnlEscritorio.setLayout(dpnlEscritorioLayout);
        dpnlEscritorioLayout.setHorizontalGroup(
            dpnlEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1329, Short.MAX_VALUE)
        );
        dpnlEscritorioLayout.setVerticalGroup(
            dpnlEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        getContentPane().add(dpnlEscritorio, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jmEmpresa.setText("Empresa");
        jmEmpresa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jmiDepartamentos.setText("Departamentos");
        jmiDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDepartamentosActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiDepartamentos);

        jmiNuevoDepartamento.setText("Nuevo Departamento");
        jmiNuevoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoDepartamentoActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiNuevoDepartamento);

        jmiCargos.setText("Cargos");
        jmiCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargosActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiCargos);

        jmiNuevoCargo.setText("Nuevo Cargo");
        jmiNuevoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoCargoActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiNuevoCargo);

        jmiEmpleados.setText("Empleados");
        jmiEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmpleadosActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiEmpleados);

        jmiNuevoEmpleado.setText("Nuevo Empleado");
        jmiNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoEmpleadoActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiNuevoEmpleado);

        jmiUsuarios.setText("Usuarios");
        jmEmpresa.add(jmiUsuarios);

        jmiNuevoUsuario.setText("Nuevo Usuario");
        jmEmpresa.add(jmiNuevoUsuario);

        jmiSucursal.setText("Sucursal");
        jmiSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSucursalActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiSucursal);

        jmiNuevaSucursal.setText("Nueva Sucursal");
        jmiNuevaSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaSucursalActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiNuevaSucursal);

        jMenuBar1.add(jmEmpresa);

        jMenu2.setText("Clientes");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jmiClientes);

        jmiNuevoCliente.setText("Nuevo Cliente");
        jmiNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNuevoCliente);

        jMenuBar1.add(jMenu2);

        jmCuentas.setText("Cuentas");
        jmCuentas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jmiCuentas.setText("Cuentas");
        jmiCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCuentasActionPerformed(evt);
            }
        });
        jmCuentas.add(jmiCuentas);

        jmiNuevoCuenta.setText("Nueva Cuenta");
        jmiNuevoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoCuentaActionPerformed(evt);
            }
        });
        jmCuentas.add(jmiNuevoCuenta);

        jMenuBar1.add(jmCuentas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNuevoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoDepartamentoActionPerformed
        // TODO add your handling code here:
        
        frmNuevoDepartamentoEmpresa frmNuevoDep = new frmNuevoDepartamentoEmpresa();
        dpnlEscritorio.add(frmNuevoDep);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmNuevoDep.getSize();
        frmNuevoDep.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmNuevoDep.setVisible(true);
        
    }//GEN-LAST:event_jmiNuevoDepartamentoActionPerformed

    private void jmiDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDepartamentosActionPerformed
        frmIndexDepatamentosEmpresa frmIndex =new frmIndexDepatamentosEmpresa();
        dpnlEscritorio.add(frmIndex);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmIndex.getSize();
        frmIndex.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmIndex.setVisible(true);
    }//GEN-LAST:event_jmiDepartamentosActionPerformed

    private void jmiCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargosActionPerformed
        frmIndexCargo frmIndex =new frmIndexCargo();
        dpnlEscritorio.add(frmIndex);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmIndex.getSize();
        frmIndex.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmIndex.setVisible(true);
    }//GEN-LAST:event_jmiCargosActionPerformed

    private void jmiNuevoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoCargoActionPerformed
        frmNuevoCargo frmNuevo = new frmNuevoCargo();
        dpnlEscritorio.add(frmNuevo);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmNuevo.getSize();
        frmNuevo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmNuevo.setVisible(true);
    }//GEN-LAST:event_jmiNuevoCargoActionPerformed

    private void jmiEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmpleadosActionPerformed
        frmIndexEmpleado frmIndex =new frmIndexEmpleado();
        dpnlEscritorio.add(frmIndex);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmIndex.getSize();
        frmIndex.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmIndex.setVisible(true);
    }//GEN-LAST:event_jmiEmpleadosActionPerformed

    private void jmiNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoEmpleadoActionPerformed
        frmNuevoEmpleado frmNuevo = new frmNuevoEmpleado();
        dpnlEscritorio.add(frmNuevo);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmNuevo.getSize();
        frmNuevo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmNuevo.setVisible(true);
    }//GEN-LAST:event_jmiNuevoEmpleadoActionPerformed

    private void jmiSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSucursalActionPerformed
        frmIndexSucursal frmIndex =new frmIndexSucursal();
        dpnlEscritorio.add(frmIndex);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmIndex.getSize();
        frmIndex.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmIndex.setVisible(true);
    }//GEN-LAST:event_jmiSucursalActionPerformed

    private void jmiNuevaSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaSucursalActionPerformed
        frmNuevoSucursal frmNuevo = new frmNuevoSucursal();
        dpnlEscritorio.add(frmNuevo);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmNuevo.getSize();
        frmNuevo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmNuevo.setVisible(true);
    }//GEN-LAST:event_jmiNuevaSucursalActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        frmIndexCliente frmIndex =new frmIndexCliente();
        dpnlEscritorio.add(frmIndex);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmIndex.getSize();
        frmIndex.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmIndex.setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoClienteActionPerformed
        frmNuevoCliente frmNuevo = new frmNuevoCliente();
        dpnlEscritorio.add(frmNuevo);
        Dimension desktopSize = dpnlEscritorio.getSize();
        Dimension FrameSize = frmNuevo.getSize();
        frmNuevo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frmNuevo.setVisible(true);
    }//GEN-LAST:event_jmiNuevoClienteActionPerformed

    private void jmiCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCuentasActionPerformed

    private void jmiNuevoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiNuevoCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEscritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dpnlEscritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCuentas;
    private javax.swing.JMenu jmEmpresa;
    private javax.swing.JMenuItem jmiCargos;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiCuentas;
    private javax.swing.JMenuItem jmiDepartamentos;
    private javax.swing.JMenuItem jmiEmpleados;
    private javax.swing.JMenuItem jmiNuevaSucursal;
    private javax.swing.JMenuItem jmiNuevoCargo;
    private javax.swing.JMenuItem jmiNuevoCliente;
    private javax.swing.JMenuItem jmiNuevoCuenta;
    private javax.swing.JMenuItem jmiNuevoDepartamento;
    private javax.swing.JMenuItem jmiNuevoEmpleado;
    private javax.swing.JMenuItem jmiNuevoUsuario;
    private javax.swing.JMenuItem jmiSucursal;
    private javax.swing.JMenuItem jmiUsuarios;
    // End of variables declaration//GEN-END:variables
}
